### ISSUE TITLE
Missing "sample_test_baseline.txt"

### ISSUE THREAD

**Issue by Huffon** [tagoyal/sow-reap-paraphrasing#1]
Hi,
Thanks for the interesting work and code base!

I would like to use my dataset to get inference result and README said I need to run the CoreNLP parser on a dataset with the same scheme as `sample_test_baseline.txt`.

And it seems that there is no `sample_test_baseline.txt` in the repository.
Could you upload `sample_test_baseline.txt`?

```
To generate this file for your custom dataset, 
run the following command (from the stanford parser folder) on a file 
with the same input scheme as the sample_test_baseline.txt
```

Thanks!

**Comment by tagoyal** [comment]
Hey, thanks for pointing that out! sample_test_baseline.txt is just a text file with the following format:

input_sentence1
gold_output_sentence1
input_sentence2
gold_output_sentence2
...
...
...
...
input_sentence_n
gold_output_sentence_n

I will update the repo with a sample
