### ISSUE TITLE
where is the weights.hdf5 and options.hdf5 files described in Training data for SOW

### ISSUE THREAD

**Issue by TITC** [tagoyal/sow-reap-paraphrasing#10]
Here is a description found at [Training data for SOW](https://github.com/tagoyal/sow-reap-paraphrasing/tree/master/processing#training-data-for-sow)
```
The code also requires ELMO representations for each input sentence. 
For these, download the weights.hdf5 and options.hdf5 file for ELMO and place it in a folder. 
Set ELMO_WEIGHTS_FOLDER as the path to this folder.
```
but I haven't found any files named with weights.hdf5 and options.hdf5, does such files is substitute by any  ELMO pre-trained models?

**Comment by tagoyal** [comment]
Refer to this repo: https://github.com/allenai/bilm-tf

**Comment by TITC** [comment]
Thanks
