### ISSUE TITLE
allenlp error

### ISSUE THREAD

**Issue by TITC** [tagoyal/sow-reap-paraphrasing#12]
when I run sh create_sow_data.sh in google colab ,it give me fellow information.
I have installed the requirement.txt.
could you give me any advice?
```
/content/sow-reap-paraphrasing/processing# sh create_sow_data.sh
mkdir: cannot create directory ‘/content/sow-reap-paraphrasing/sow_intermediate’: File exists
Traceback (most recent call last):
  File "get_elmo_embeds.py", line 1, in <module>
    from allennlp.commands.elmo import ElmoEmbedder
ImportError: No module named allennlp.commands.elmo
```
my allennlp version is 0.8.0.

**Comment by TITC** [comment]
I found at[ annlennlp official website](https://github.com/allenai/allennlp/issues/4384#issuecomment-646724327) it give below account:
---
We removed the elmo command in v1.0. If you want to use the elmo command then you need to check out v0.9.0. We removed this command because elmo is becoming a bit old and we didn't think it made sense to continue supporting it as a top-level command.

What are you trying to do specifically? You might still be able to accomplish your goals in 1.0, but I'm not sure exactly what you're trying to do.

---

but my allennlp version is earlier than 0.9.0, it still not work.

**Comment by TITC** [comment]
can I replace it with other modules?
```
from allennlp.commands.elmo import ElmoEmbedder
```

**Comment by tagoyal** [comment]
Yes. 
I'm currently  a little busy with a deadline, but if issues still persists, I can look at them after Tuesday.

**Comment by TITC** [comment]
ok, first things first.

**Comment by TITC** [comment]
> Yes.
> I'm currently a little busy with a deadline, but if issues still persists, I can look at them after Tuesday.

the problem still exists. I only successfully install it by coincidence and can't reproduce it anymore.

but due do I think it can be replaced by BERT EMbedding, so as I think problem solved.

**Comment by TITC** [comment]
problem solved directly by [this issue](https://github.com/allenai/allennlp/issues/5203#issue-892618996).

**Comment by TITC** [comment]
![image](https://user-images.githubusercontent.com/35098797/119205739-b7389c00-bacb-11eb-89a5-3f3becc18bf3.png)
