### ISSUE TITLE
Paraphrasing custom data and pythonic dependencies

### ISSUE THREAD

**Issue by atreyasha** [tagoyal/sow-reap-paraphrasing#2]
First off, thank you for the insightful paper and for releasing your code. I would like to use your model(s) to ultimately paraphrase some custom datasets for machine translation tasks.

I was wondering which functions could I use for generating paraphrases on custom data? I looked through `README.md` under inference, but I think the instructions with input files like `sample_test_baseline.txt` only apply when there are gold paraphrases.

Thank you for your time.

**Comment by tagoyal** [comment]
The code doesn't really use the gold paraphrase for generation, only uses it to compute the perplexity. So you could provide any dummy gold paraphrase as input and ignore the perplexity and gold paraphrase outputs in the output file. 

Hope this helps!

**Comment by atreyasha** [comment]
Thank you for the clarification, I will try that out. Closing this issue.

**Comment by atreyasha** [comment]
Additionally:

1. Could you upload a `requirements.txt` file? That would help with syncing dependencies.

2. Which python version did you use for your tests?

**Comment by tagoyal** [comment]
done. let me know if you face other issues!

**Comment by atreyasha** [comment]
Awesome, thank you :+1:

**Comment by atreyasha** [comment]
Regarding `requirements.txt`:

```
mock==2.0.0
numpy==1.17.1
h5py==2.9.0
six==1.12.0
~orch==1.2.0
torchvision==0.4.0
adabound==0.0.5
bokeh==2.0.2
hyperdash==0.15.3
pandas==1.0.3
scikit_learn==0.23.0
torch==1.5.0
```

`Pip` failed deciphering `~orch` and `torch`. I am guessing there was a typo and it should be `torch`. Which version is the correct one, `1.2.0` or `1.5.0`?

**Comment by tagoyal** [comment]
It's version 1.5.0
will fix.

**Comment by atreyasha** [comment]
I see. I changed it locally and tried re-installing, but `pip` outputs a warning:

"ERROR: torchvision 0.4.0 has requirement torch==1.2.0, but you'll have torch 1.5.0 which is incompatible."

I have not tested, but would this break something in the pipeline?

**Comment by tagoyal** [comment]
hm, this is weird, this is the exact input of my pip freeze

torch==1.5.0
torchvision==0.4.0

Though downgrading it shouldn't break anything in the code.

**Comment by atreyasha** [comment]
Hmm, yes strange. I tested with `torch==1.2.0` and everything still works. I think I will keep it at this version because our servers are not configured with the latest CUDA versions required for `1.5.0` :/

**Comment by TITC** [comment]
same with you

> hm, this is weird, this is the exact output of my pip freeze
> 
> torch==1.5.0
> torchvision==0.4.0
> 
> Though downgrading it shouldn't break anything in the code.

---
```
INFO: pip is looking at multiple versions of numpy to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of mock to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r /content/sow-reap-paraphrasing/requirements.txt (line 5) and torch==1.5.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested torch==1.5.0
    torchvision 0.4.0 depends on torch==1.2.0
```
