### ISSUE TITLE
how generate train_sow.hdf5 file 

### ISSUE THREAD

**Issue by jiezouguihuafu** [tagoyal/sow-reap-paraphrasing#3]
train_sow.hdf5 I want to train SOW model ，but it need  train_sow.hdf5 file . And the file how to get？

**Comment by tagoyal** [comment]
it's there in the google drive link (in the readme) under the data folder.

**Comment by jiezouguihuafu** [comment]
> it's there in the google drive link (in the readme) under the data folder.

if I want to train at myself data set，then，how to generate this file？

**Comment by tagoyal** [comment]
Ok, I'll upload that code in a couple fo days.

**Comment by TITC** [comment]
when i run the filter_data.py in google colab
`
python filter_data.py --input_file [input_file] --output_file [output_file] --wordEmbed_file [wordEmbed_file]
`
adjust filter_data as below for debug purpose in vscode
```
if __name__ == '__main__':
    args = parser.parse_args()
    args.input_file = "/content/sow-reap-paraphrasing/sample_test_baseline.txt"
    args.output_file = "/content/sow-reap-paraphrasing/sample_test_output.txt"
    args.wordEmbed_file = "/content/sow-reap-paraphrasing/data/glove/glove.6B.50d.txt"
    input_file = args.input_file
    output_file = args.output_file
    wordEmbed_file = args.wordEmbed_file
```
and it shows 
![image](https://user-images.githubusercontent.com/35098797/118207792-fe090f00-b497-11eb-8dee-a8b109217e3f.png)

when I check the variable embed1, it looks not a numerical vector
![image](https://user-images.githubusercontent.com/35098797/118207949-50e2c680-b498-11eb-9066-2b564fd7df35.png)
