### ISSUE TITLE
Is the test data available? 

### ISSUE THREAD

**Issue by berlino** [tagoyal/sow-reap-paraphrasing#9]
Hi,

  Thanks for sharing the great resource for paraphrasing!
 
  I'm wondering if the test set is available somewhere. I noticed the google drive  only contains train and dev, and in the paper you mentioned the evaluation is conducted on 10k examples from ParaNMT-50m. 

Thanks

**Comment by tagoyal** [comment]
Hi, 
I've uploaded the test data in the data folder of the google drive.
